M48
; DRILL file {KiCad 8.0.7} date 2025-06-17T21:45:14-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-17T21:45:14-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X153.0Y-84.0
X153.0Y-104.0
X154.0Y-114.0
X184.0Y-114.0
T2
X48.0Y-74.0
X48.0Y-114.0
X222.0Y-74.0
X222.0Y-114.0
M30
